### ISSUE TITLE
invalid pointer casts (byteSwap)

### ISSUE THREAD

**Issue by skliper** [nasa/elf2cfetbl#1]
Originated by glimes (31 on babelfish):

cppcheck has a very useful warning about invalid pointer casts which is triggered by the a call to byteSwap. We could patch this with a double-cast ... or we could fix it, by having byteSwap take a (void*) pointer parameter. But fixing it is a good idea, so future cppcheck messages about this condition are more useful.

**Comment by avan989** [comment]
I do not see any call to byteSwap in this tool.

**Comment by skliper** [comment]
Could you run cppcheck on the code and confirm there are no invalid pointer cast warnings?

**Comment by avan989** [comment]
No warning when I did cppcheck:

```
anh@anh-VirtualBox:/media/sf_share/elf2cfetbl$ cppcheck elf2cfetbl.c
Checking elf2cfetbl.c ...
anh@anh-VirtualBox:/media/sf_share/elf2cfetbl$ 

```

**Comment by skliper** [comment]
Ran with:
`cppcheck --enable=performance,portability,warning --std=c99 --std=posix --inconclusive -j 8 *`

and confirmed no pointer cast error exists.
