### ISSUE TITLE
Possible world-writable file creation, LGTM warning

### ISSUE THREAD

**Issue by avan989** [nasa/elf2cfetbl#28]
**Describe the bug**
LGTM warning: A file may be created here with mode 0666, which would make it world-writable.
https://github.com/nasa/elf2cfetbl/blob/eb5e326a3c85af2dd34735913881f8e15db808db/elf2cfetbl.c#L1446-L1464

**To Reproduce**
1. Build against lgtm 

**Reporter Info**
Anh Van, NASA Goddard

*EDIT* - removed warnings covered by other issues (split)
*EDIT* - updated per latest warning

**Comment by skliper** [comment]
See #58 and #57, split from this issue.

**Comment by skliper** [comment]
See #60 split from this issue

**Comment by skliper** [comment]
This turns out to be a duplicated of #54, remaining warning is a false alarm.
