### ISSUE TITLE
elf2cfetbl crashes when destination file not found

### ISSUE THREAD

**Issue by skliper** [nasa/elf2cfetbl#3]
Originated by Thadeus (65 on babelfish):

When the destination filename cannot be found in the table object file, the destination object file is not opened. However, the FreeMemoryAllocations function unconditionally calls fclose on its pointer, which segfaults when it is NULL. Initializing both file pointers to NULL and checking them before calling fclose prevents the segfault.

[0001-Prevent-a-segfault-in-elf2cfetbl.txt](https://github.com/nasa/elf2cfetbl/files/3322545/0001-Prevent-a-segfault-in-elf2cfetbl.txt)

**Comment by skliper** [comment]
@avan989 will your fix to #17 also fix this crash?

**Comment by avan989** [comment]
No, fix #17 will not fix this issue.
