### ISSUE TITLE
elf2cfetbl classic build include path order issues

### ISSUE THREAD

**Issue by skliper** [nasa/elf2cfetbl#4]
Originated by abrown (67 on babelfish):

elf2cfetbl Makefile doesn't include paths in the correct order (classic build)

Using cFE 6.5.0a with the "classic" makefile system: the tools/elf2cfetbl/for_build/Makefile has include paths in the wrong order such that it always picks up config files from the defined source first, rather than what is in your actual mission or local build directory. Ex: you change OS_MAX_FILE_NAME in your flight build and there is a table header mismatch with elf2cfetbl.

**Comment by skliper** [comment]
Really just need to deprecate/cleanup/remove classic build artifacts.

**Comment by skliper** [comment]
@avan989 - want to take this one?  Just delete for_build and the top Makefile.  Both are obsolete.

**Comment by avan989** [comment]
sure
