### ISSUE TITLE
elf2cfetbl internal filename/path length dependency on OSAL questionable

### ISSUE THREAD

**Issue by skliper** [nasa/elf2cfetbl#5]
Originated by abrown4 (68 on babelfish):

The internal filename/path length for the table files produced do NOT have to depend upon the OSAL. The OSAL OS_MAX_FILE_NAME limit is too restrictive. Need to use the PATH_MAX from linux/limits.h that is appropriate for the host.

JH - Suggest possibly checking size against OSAL and notify user when limit exceeded (but still allow to run as long as it meets PATH_MAX).

**Comment by avan989** [comment]
I can do this.
