### ISSUE TITLE
Remove workflow branch restrictions, add duplicate check, fix format check name

### ISSUE THREAD

**Issue by astrogeco** [nasa/elf2cfetbl#83]
**Describe the bug**

The format check and static analysis workflows only run on pushes to main or on pull requests so community users will not get the alerts on their forks. 

The CodeQL workflow may run on pull requests to branches other than `main` 

**To Reproduce**
Fork repo, commit new branch: format check and static analysis workflows aren't triggered. 

**Expected behavior**
All workflows run on fork branches, even those without pull requests. 

**Code snips**
https://github.com/nasa/elf2cfetbl/blob/3eeae683cca418322077e89bea587cb3f1159354/.github/workflows/format-check.yml#L4-L9

https://github.com/nasa/elf2cfetbl/blob/3eeae683cca418322077e89bea587cb3f1159354/.github/workflows/static-analysis.yml#L4-L9

https://github.com/nasa/elf2cfetbl/blob/3eeae683cca418322077e89bea587cb3f1159354/.github/workflows/codeql-build.yml#L3-L8

**System observed on:**
GitHub

**Additional context**
Should also add check-for-duplicates job to workflows after relaing the branch requirement on the push trigger

**Reporter Info**
Full name and company/organization if applicable

**Comment by skliper** [comment]
Closed by #97
